/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 12-dub-2021 18:32:33 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS adresa_adresaid_seq
;

DROP SEQUENCE IF EXISTS alergen_cislo_seq
;

DROP SEQUENCE IF EXISTS jidlo_jidloid_seq
;

DROP SEQUENCE IF EXISTS menu_menuid_seq
;

DROP SEQUENCE IF EXISTS objednavkajidla_objednavkajidlaid_seq
;

DROP SEQUENCE IF EXISTS rezervace_rezervaceid_seq
;

DROP SEQUENCE IF EXISTS rozvrh_rozvrhid_seq
;

DROP SEQUENCE IF EXISTS stul_stulid_seq
;

DROP SEQUENCE IF EXISTS uzivatel_uzivatelid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Adresa" CASCADE
;

DROP TABLE IF EXISTS "Alergen" CASCADE
;

DROP TABLE IF EXISTS "je soucasti   " CASCADE
;

DROP TABLE IF EXISTS "je zarezervovan" CASCADE
;

DROP TABLE IF EXISTS "Jidlo" CASCADE
;

DROP TABLE IF EXISTS "Menu" CASCADE
;

DROP TABLE IF EXISTS "ObjednavkaJidla" CASCADE
;

DROP TABLE IF EXISTS "obsahuje" CASCADE
;

DROP TABLE IF EXISTS "prebyva na adrese" CASCADE
;

DROP TABLE IF EXISTS "Rezervace" CASCADE
;

DROP TABLE IF EXISTS "Rozvrh" CASCADE
;

DROP TABLE IF EXISTS "Stul" CASCADE
;

DROP TABLE IF EXISTS "Uzivatel" CASCADE
;

/* Create Tables */

CREATE TABLE "Adresa"
(
	"Mesto" varchar(50) NULL,
	"Psc" integer NULL,
	"Stat" varchar(50) NULL,
	"Ulice" varchar(50) NULL,
	"AdresaID" integer NOT NULL   DEFAULT NEXTVAL(('"adresa_adresaid_seq"'::text)::regclass)
)
;

CREATE TABLE "Alergen"
(
	"Cislo" integer NOT NULL   DEFAULT NEXTVAL(('"alergen_cislo_seq"'::text)::regclass),
	"Nazev" varchar(50) NULL
)
;

CREATE TABLE "je soucasti   "
(
	"JidloID" integer NULL,
	"Cislo" integer NULL
)
;

CREATE TABLE "je zarezervovan"
(
	"RezervaceID" integer NULL,
	"StulID" integer NULL
)
;

CREATE TABLE "Jidlo"
(
	"Cena" integer NULL,
	"Nazev" varchar(50) NULL,
	"JidloID" integer NOT NULL   DEFAULT NEXTVAL(('"jidlo_jidloid_seq"'::text)::regclass),
	"ObjednavkaJidlaID" integer NULL
)
;

CREATE TABLE "Menu"
(
	"Platnostdo" date NULL,
	"Platnostod" date NULL,
	"MenuID" integer NOT NULL   DEFAULT NEXTVAL(('"menu_menuid_seq"'::text)::regclass)
)
;

CREATE TABLE "ObjednavkaJidla"
(
	"Pocet" integer NULL,
	"ObjednavkaJidlaID" integer NOT NULL   DEFAULT NEXTVAL(('"objednavkajidla_objednavkajidlaid_seq"'::text)::regclass)
)
;

CREATE TABLE "obsahuje"
(
	"MenuID" integer NULL,
	"JidloID" integer NULL
)
;

CREATE TABLE "prebyva na adrese"
(
	"AdresaID" integer NULL,
	"UzivatelID" integer NULL
)
;

CREATE TABLE "Rezervace"
(
	"Datumdo" date NULL,
	"Datumod" date NULL,
	"RezervaceID" integer NOT NULL   DEFAULT NEXTVAL(('"rezervace_rezervaceid_seq"'::text)::regclass),
	"ObjednavkaJidlaID" integer NULL,
	"UzivatelID" integer NULL
)
;

CREATE TABLE "Rozvrh"
(
	"Datumdo" date NULL,
	"Datumod" date NULL,
	"Jedostupny" boolean NULL,
	"RozvrhID" integer NOT NULL   DEFAULT NEXTVAL(('"rozvrh_rozvrhid_seq"'::text)::regclass),
	"StulID" integer NULL
)
;

CREATE TABLE "Stul"
(
	"Pocetmist" integer NULL,
	"StulID" integer NOT NULL   DEFAULT NEXTVAL(('"stul_stulid_seq"'::text)::regclass)
)
;

CREATE TABLE "Uzivatel"
(
	"Email" varchar(50) NULL,
	"Jmeno" varchar(50) NULL,
	"Prijmeni" varchar(50) NULL,
	"Telefon" varchar(50) NULL,
	"UzivatelID" integer NOT NULL   DEFAULT NEXTVAL(('"uzivatel_uzivatelid_seq"'::text)::regclass)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Adresa" ADD CONSTRAINT "PK_Adresa"
	PRIMARY KEY ("AdresaID")
;

ALTER TABLE "Alergen" ADD CONSTRAINT "PK_Alergen"
	PRIMARY KEY ("Cislo")
;

ALTER TABLE "Jidlo" ADD CONSTRAINT "PK_Jidlo"
	PRIMARY KEY ("JidloID")
;

ALTER TABLE "Menu" ADD CONSTRAINT "PK_Menu"
	PRIMARY KEY ("MenuID")
;

ALTER TABLE "ObjednavkaJidla" ADD CONSTRAINT "PK_ObjednavkaJidla"
	PRIMARY KEY ("ObjednavkaJidlaID")
;

ALTER TABLE "Rezervace" ADD CONSTRAINT "PK_Rezervace"
	PRIMARY KEY ("RezervaceID")
;

ALTER TABLE "Rozvrh" ADD CONSTRAINT "PK_Rozvrh"
	PRIMARY KEY ("RozvrhID")
;

ALTER TABLE "Stul" ADD CONSTRAINT "PK_Stul"
	PRIMARY KEY ("StulID")
;

ALTER TABLE "Uzivatel" ADD CONSTRAINT "PK_Uzivatel"
	PRIMARY KEY ("UzivatelID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "je soucasti   " ADD CONSTRAINT "FK_je soucasti   _Alergen"
	FOREIGN KEY ("Cislo") REFERENCES "Alergen" ("Cislo") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "je soucasti   " ADD CONSTRAINT "FK_je soucasti   _Jidlo"
	FOREIGN KEY ("JidloID") REFERENCES "Jidlo" ("JidloID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "je zarezervovan" ADD CONSTRAINT "FK_je zarezervovan_Rezervace"
	FOREIGN KEY ("RezervaceID") REFERENCES "Rezervace" ("RezervaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "je zarezervovan" ADD CONSTRAINT "FK_je zarezervovan_Stul"
	FOREIGN KEY ("StulID") REFERENCES "Stul" ("StulID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Jidlo" ADD CONSTRAINT "FK_Jidlo_je soucasti"
	FOREIGN KEY ("ObjednavkaJidlaID") REFERENCES "ObjednavkaJidla" ("ObjednavkaJidlaID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "obsahuje" ADD CONSTRAINT "FK_obsahuje_Menu"
	FOREIGN KEY ("MenuID") REFERENCES "Menu" ("MenuID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "obsahuje" ADD CONSTRAINT "FK_obsahuje_Jidlo"
	FOREIGN KEY ("JidloID") REFERENCES "Jidlo" ("JidloID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "prebyva na adrese" ADD CONSTRAINT "FK_prebyva na adrese_Adresa"
	FOREIGN KEY ("AdresaID") REFERENCES "Adresa" ("AdresaID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "prebyva na adrese" ADD CONSTRAINT "FK_prebyva na adrese_Uzivatel"
	FOREIGN KEY ("UzivatelID") REFERENCES "Uzivatel" ("UzivatelID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Rezervace" ADD CONSTRAINT "FK_Rezervace_patri k"
	FOREIGN KEY ("ObjednavkaJidlaID") REFERENCES "ObjednavkaJidla" ("ObjednavkaJidlaID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Rezervace" ADD CONSTRAINT "FK_Rezervace_si zarezervoval"
	FOREIGN KEY ("UzivatelID") REFERENCES "Uzivatel" ("UzivatelID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Rozvrh" ADD CONSTRAINT "FK_Rozvrh_dostupnost se ridi podle"
	FOREIGN KEY ("StulID") REFERENCES "Stul" ("StulID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE adresa_adresaid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE alergen_cislo_seq INCREMENT 1 START 1
;

CREATE SEQUENCE jidlo_jidloid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE menu_menuid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE objednavkajidla_objednavkajidlaid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE rezervace_rezervaceid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE rozvrh_rozvrhid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE stul_stulid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE uzivatel_uzivatelid_seq INCREMENT 1 START 1
;
